import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'event-viewer',
  templateUrl: './event-viewer.component.html',
  styleUrls: ['./event-viewer.component.scss','./../daas.component.scss']
})
export class EventViewerComponent implements OnInit {

  constructor() { }

  title:string = "Application Event Logs";
  description:string = "View Event Logs containing exceptions and errors generated by your app";

  ngOnInit() {
  }

}
